export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';

export const GET_IMAGES_OF_USER = 'GET_IMAGES_OF_USER';
